### ISSUE TITLE
Skin tone slider not working

### ISSUE THREAD

**Issue by lalalune** [AtlasFoundation/OpenCharacterCreator#12]
![image](https://user-images.githubusercontent.com/18633264/170871047-a90504a2-2b3b-4722-b31f-4a9e7c0e94cc.png)

**Comment by DavinciDreams** [comment]
Can we use a color wheel instead? [react native colorwheel](https://github.com/netbeast/react-native-color-wheel) @lalalune

**Comment by fire** [comment]
Recommend you use color swatches and a wheel.
